using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace meters
{
    public delegate void En_delegate();
    public delegate void dellegate_del_histiry_ship();
    class Globals
    {
        public static En_delegate en_delegate;
        public static En_delegate en_delegate_cmol;
        public static En_delegate en_delegate_return;
        public static En_delegate en_delegate_operator;
        public static dellegate_del_histiry_ship del_histiry_ship;
        public static int id_slujbi;
        public static int id_current_doc;
        public static int id_user;
        public static string name_user;
        public static string name_slujbi;
        public static int id_access;
        public static int userId4SCM;
        public static int main_menu;
        public static int id_doc_materials;
        public static int id_doc_materials2;
        public static string add;
        public static int id_doc_materials_for_main;
        public static DateTime date_mater;
        public static Boolean doc_status;
        public static int id_doc_meter_mol_docs;
        public static int id_doc_meter_mol_docs2;
        public static int id_doc_meter_for_main;
        public static string str;
        public static string wtr;
        public static string znum;
        public static int id_meter_type;
        public static Boolean meter_doc_status;
        public static int id_Shipments_for_status;
        public static int id_Part_Meter;
        public static int id_Shipments;
        public static int ship_stat;
        public static int id_Meter_Status;
        public static string str_sim;
        public static int id_sim;
        public static string number_sim;
        public static int Quantity;
        public static int Part_Meter_status;
        public static int id_install_doc;
        ///////peremennye dlya korrektirovki////
        public static int id_correct_row;
        public static int id_Installed;
           public static int id_Executor_Importer;
           public static int tpNo;
           public static int id_NewMeter;
            public static  Decimal NewReadings;
            public static string Seal_TermCover;
            public static string Seal_GP;
            public static string Seal_MCB;
            public static string Seal_CRPU;
            public static string Seal_Box;
            public static string Seal_Modem;
            public static string Seal_CT;
            public static string Type_Customer;
            public static string CustomerCode;
            public static string CustomerName;
           public static string Address;
            public static string Dom_kv;
           public static string OldMeterNo;
           public static  Decimal OldReadings;
            public static string OldMeterType;
           public static int id_Cable;
           public static  Decimal CableLength;
           public static int id_MCB;
           public static int id_Box;
           public static int id_Edit;
           public static Boolean BillingCheck;
            public static Boolean EditStatus;
            public static int TT;
            public static string Correct_cspot;
            public static string Correct_counters;
        /////////мадина
            public static int id_history_meter_ship;
            public static int i_posishion;
            public static int id_ship;
            public static int id_sim2;
            public static int id_tp;
            public static int id_akt;
            public static int id_rab;
            public static string add2;
            public static int status;
            public static string sm_name;
            public static int y;
            public static string str2;
            public static double kol_akt;
            public static int id_installedMeters2;
            public static int id_partt;
            public static int id_region;
            public static string tp_name;
            public static string fider_name;
            public static string fider_n;
            public static int id_schet_hist;
            public static string crpu;
            public static string modem;
            public static DateTime Date_installed;
            public static int instMAT;
            public static int id_installer2;
            public static string correct_old_meter_type;
            public static string vid;
            public static int mes_index;
            public static int id_master;
            public static string master_vpu;
            public static DateTime Date_n;
            public static DateTime Date_k;
            //adiltai
            public static DateTime date1;
            public static DateTime date2;
            public static string nameAKT;
            public static int partQuantity;
            public static int godd;
            public static DateTime Date_return;
            public static int NameImportReturn;
            public static int NameExportReturn;
            public static int year_index;
            public static int returnDeffID;
            public static int returnDefId;
            public static int idTypeM;
            public static int idInst2;
            public static int idNmet;
            public static int iddeffect;
            public static Boolean docdeffetM;
            public static int SimIDdeff;
            public static int idShipDeff;
            public static int idDeff2;
            public static int statusDEff;
            public static int Current_doc_CRPUissud;
            public static int TypeRep;
        //api            
            public static string url;
            public static string username;
            public static string password;
            public static string sessionId;

    }
}
