using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraTreeList.Nodes;
using DevExpress.XtraTreeList;

namespace meters
{
    public partial class obor : Form
    {
        public obor()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            spr_resTableAdapter1.Fill(mmsDataSet11.spr_res);
        }

      
        private void obor_Load(object sender, EventArgs e)
        {
            spr_resTableAdapter1.Fill(mmsDataSet11.spr_res);
            spr_regionbilling_tpTableAdapter.Fill_tp(mMSDataSet.spr_regionbilling_tp,Globals.id_region,Globals.tp_name);
        }


        //private string GetSelectedNode(TreeList trvTreeList)
        //{
        //    //if (trvTreeList.Columns["id_obor"]==null)
        //    //{
        //    //    return "";
        //    //} 
        //    try
        //    { Globals.vid=trvTreeList.FocusedNode[trvTreeList.Columns["vid"]].ToString();
        //        if (Convert.ToInt32(Globals.vid)==4)
        //        {
        //        string fff = trvTreeList.FocusedNode[trvTreeList.Columns["id"]].ToString();
        //        string fff1 = trvTreeList.FocusedNode[trvTreeList.Columns["id_res"]].ToString();
             
        //        string name_obor = trvTreeList.FocusedNode[trvTreeList.Columns["slujbi"]].ToString();
        
        //        Globals.id_region = Convert.ToInt32(fff1);
        //        Globals.tp_name = name_obor;
               
        //        }
        //    }
        //    catch { return ""; }

        //}
          private void treeList1_AfterFocusNode(object sender, NodeEventArgs e)
            {
           Globals.vid=treeList1.FocusedNode[treeList1.Columns["vid"]].ToString();
           if (Convert.ToInt32(Globals.vid) == 4)
           {
               string fff = treeList1.FocusedNode[treeList1.Columns["id"]].ToString();
               string fff1 =treeList1.FocusedNode[treeList1.Columns["id_res"]].ToString();

               string name_obor = treeList1.FocusedNode[treeList1.Columns["slujbi"]].ToString();

               Globals.id_region = Convert.ToInt32(fff1);
               Globals.tp_name = name_obor;
               if (Convert.ToInt32(Globals.vid) == 4)
               {
                   this.spr_regionbilling_tpTableAdapter.Fill_tp(this.mMSDataSet.spr_regionbilling_tp, Globals.id_region, Globals.tp_name);
               }
           }
            }

            private void treeList1_CustomFilterDisplayText(object sender, DevExpress.XtraEditors.Controls.ConvertEditValueEventArgs e)
            {
                treeList1.ExpandAll();
            }
		
    }
}
